services:
  api:
    container_name: todo-app-api-go
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    command: air
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: todo-app-mysql-go
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    command: --host_cache_size=0 --pid-file=/var/run/mysqld/mysqld.pid
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword" ]
      interval: 10s
      retries: 5

volumes:
  mysql_data:
  mysql_config:
